-- Create newsletter subscribers table
create table if not exists "public"."67f8434b14dfafddebe24d2a_newsletter" (
  "id" bigint generated by default as identity,
  "created_at" timestamp with time zone default now() not null,
  "email" text not null,
  "user_id" uuid,

  primary key ("id")
);

-- Create membership signups table
create table if not exists "public"."67f8434b14dfafddebe24d2a_membership_signups" (
  "id" bigint generated by default as identity,
  "created_at" timestamp with time zone default now() not null,
  "email" text not null,
  "name" text not null,
  "membership_type" text not null,
  "signup_date" timestamp with time zone not null,
  "user_id" uuid,

  primary key ("id")
);